### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by tezakaftor** [bonukai/MediaTracker#1]
Hi!
Thank you for a nice application. I was trying your application via docker and found two bugs regarding settings in the application.
I'm not able to disable registration or change password.

**Comment by bonukai** [comment]
This should be now fixed

**Comment by tezakaftor** [comment]
Thank you! I can confirm it's working now.

**Comment by TWART016** [comment]
Where can I disable the registration for new users?

**Comment by bonukai** [comment]
Click on your username in the right top corner, and then `Configuration` on the left

**Comment by TWART016** [comment]
I cannot see ```Configuration```
![image](https://github.com/bonukai/MediaTracker/assets/29805669/2be0d951-4192-4400-a786-952dca72399c)

**Comment by bonukai** [comment]
`Configuration` is only visible for an admin. First created user has admin privileges

**Comment by TWART016** [comment]
Is it possible to assign admin role to another user or change it in an User Management?

**Comment by bonukai** [comment]
At the moment there is no user management, but even if there would be, in the website, non admin users should not be able to make other non admin privilege of the admin. However this could be solved by the command line interface, where you could reset password, or assign admin roles.

Until then, you could stop `MediaTracker`, open SQLite database `data.db` with [https://sqlitebrowser.org/](https://sqlitebrowser.org/), and manually change `admin` filed in `user` table to `1`

![image](https://github.com/bonukai/MediaTracker/assets/17750886/a8c99aec-209a-4207-9423-e5c35a5ecc09)
