### ISSUE TITLE
Unhealthy Container: curl: (7) Failed to connect to 127.0.0.1 port 7481 after 0 ms: Connection refused

### ISSUE THREAD

**Issue by URBANsUNITED** [bonukai/MediaTracker#105]
Hi!

Maybe it's on my side, but it is the only container which is unhealthy and has this issue:
![Bildschirmfoto 2022-02-09 um 09 37 05](https://user-images.githubusercontent.com/6212300/153157384-f8c9b3c7-77ff-4d75-a9e6-0ee74d258344.png)

curl: (7) Failed to connect to 127.0.0.1 port 7481 after 0 ms: Connection refused

Is it important? Is it fixable?
Taken from Portainer latest version btw.

My setup:

![Bildschirmfoto 2022-02-09 um 09 40 20](https://user-images.githubusercontent.com/6212300/153157712-5fc93f20-a889-4f5d-8cae-3297edb60863.png)

Btw. Website is not accessable on my iPhone. On the Mac using Chrome no issues, Safari doesn't work either! Only Chrome works

Thanks
URBANsUNITED

**Comment by bonukai** [comment]
Healthcheck should now be working

**Comment by URBANsUNITED** [comment]
Yep! Working! Thanks

![Bildschirmfoto 2022-02-09 um 17 20 06](https://user-images.githubusercontent.com/6212300/153243500-3b14d418-b88e-4f37-81bc-6d3b10abe0ec.png)
