### ISSUE TITLE
Reviews from other users are showed as your own

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#125]
Hi,

When you create a review, if other user go and try to review the same thing when opening the review dialog it will got the review that other user has already made instead an empty review.

Steps to replicate:
- Create a review on userA for B content including score.
- Go with userB to the same content, and press on the star.
- You will get a filled dialog instead and empty dialog.

Expected on user B:
![image](https://user-images.githubusercontent.com/11770760/153292222-97c7a83e-50bd-40c9-9585-1446fac87be8.png)
(I used another content because I don't know how to remove the score, pressing on the selected star doesn't seem to work).

What is really on user B:
![image](https://user-images.githubusercontent.com/11770760/153292126-97b2e90c-a8ef-4eb5-994c-d895ca543155.png)

BTW, how can I remove a score? I tried but didn't find out how to do so.

**Comment by bonukai** [comment]
Bug with reviews should now be fixed.

There was no way to remove rating, but now you can do it by clicking again on the same score
