### ISSUE TITLE
Error at updating title

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#159]
Hi, when I start MediaTracker I get this error:

![image](https://user-images.githubusercontent.com/11770760/154231034-e7ffe27f-7972-429f-a947-1aa18329b24c.png)

Not sure how can I debug this.

**Comment by bonukai** [comment]
Open Library API returns description in different formats. For example [here](https://openlibrary.org/works/OL82563W.json) it a `string`, but [here](https://openlibrary.org/works/OL2019091W.json) it's an object
```typescript
{ type: '/type/text'; value: string }
```

Now both format are handled correctly

**Comment by BanCrash** [comment]
Perfect, thanks!
