### ISSUE TITLE
Use translated dates from date-fns localization

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#161]
Hi,

I've tried to use the date-fns localization as stated on their documentation to show the strings in the selected language.

In client/src/date.ts I've added:
```
import { da, de, en, es } from 'date-fns/locale'

(...)

return formatDistance(to, new Date(), { locale: es, addSuffix: true });

```

And it is showing in spanish as expected:
![image](https://user-images.githubusercontent.com/11770760/154304758-4a04bbd6-b993-4d0a-a698-38e4123e92a1.png)

But I'm failing to get the sever language from lingui. I've tried copying the lingui access from Calendar.tsx, but it seems that it doesn't work that way. I never used typeScript before so I don't know how to continue, so I let you here my progress so maybe you can complete it.

**Comment by bonukai** [comment]
Thanks,

[useLingui](https://lingui.js.org/ref/react.html#useLingui) is a [React hook](https://reactjs.org/docs/hooks-intro.html) and it can only be used in other hook or component. I choose the latter, and transformed function `relativeTimeTo` to a [React Component](https://reactjs.org/docs/components-and-props.html)
