### ISSUE TITLE
Add management server settings

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#163]
Hi,

I'm currently using the npm version on Windows and closing the server is as easy as closing the terminal. But my idea is to execute this on a Synology that doesn't have docker support, and there closing the terminal won't stop the server, so I don't know how to shutdown it, nor how to check the log.

So I was thinking that could be useful that the admin user have a "Management" section on the settings where we can shutdown / restart the server and check the log.

**Comment by bonukai** [comment]
You can now view logs in the settings page [http://localhost:7481/#/settings/logs](http://localhost:7481/#/settings/logs)

**Comment by BanCrash** [comment]
It works perfect, thanks!

**Comment by bonukai** [comment]
@BanCrash mediatracker is now available on npmjs.com, you don't have to build it yourself anymore
```bash
npm install -g mediatracker
mediatracker
```

**Comment by BanCrash** [comment]
@bonukai perfect, I just tested and it works fine, thanks!

**Comment by BanCrash** [comment]
For my side this can be closed since now I have finally docker support.
