### ISSUE TITLE
/assests not used in docker

### ISSUE THREAD

**Issue by Fabaderheld** [bonukai/MediaTracker#172]
I did some more testing with in the docker container, but I looks like ```/assests``` is not used
here is the volume config
```    volumes: ['/appdata/mediatracker/storage:/storage', '/appdata/mediatracker/assets:/assets']```

I ended up with ~45Gb in ```/var/lib/docker/overlay2/```
and ```/appdata/mediatracker/assets``` is empty

**Comment by bonukai** [comment]
I forgot to implement that, all images were saved to a fixed path, `img`. Now it should work correctly. All missing posters are redownloaded when needed, that's why I missed it, and you will not loose anything.

**Comment by Fabaderheld** [comment]
:D ok copied everything from the overlay path. I'll give the new version a spin. Great support as usual

**Comment by Fabaderheld** [comment]
After recreating I get connection refused from the container, any chance something else broke?

**Comment by Fabaderheld** [comment]
Ok sorry my bad, somehow chrome was broken, reopen it fixed it.
