### ISSUE TITLE
Movie collections

### ISSUE THREAD

**Issue by SirBogner** [bonukai/MediaTracker#188]
I'm currently watching several different movie series and I am beginning to feel the "movies" tab is quite filled. 

My idea and suggestion is a possibility to create movie collections and be able to organize my mess. This could even be extended to "games", "books" and so on.

**Comment by SirBogner** [comment]
Update: 

I see this feature already planned in #110. I still do think book and audio book collections may be a good addition.

**Comment by bonukai** [comment]
On [trakt.tv](https://trakt.tv) a collection is a list of items that you own, for example in physical Blu-ray disc, and it will be the same here.

I also plan to implement lists #111 from trakt.tv. You will be able to put any item (movie, tv show, book, audiobook or game) on any list, or lists

**Comment by SirBogner** [comment]
Okay, thanks for clarifying
