### ISSUE TITLE
Sorting does not work for searches

### ISSUE THREAD

**Issue by Christoph-Wagner** [bonukai/MediaTracker#2]
After searching, it doesn’t matter what’s selected in the sorting dropdown, none of the options actually change anything. I only tested this for TV shows and books.

On a related note: The filters don’t make sense for some areas, e.g. "Next Airing" and "Unseen episodes count" for books.

**Comment by bonukai** [comment]
Unfortunately TMDB API doesn't have an option to sort search result. Sorting on search is now removed, and "Next Airing" and "Unseen episodes count" is only visible on TV Shows.

Thanks for your feedback
