### ISSUE TITLE
Tagged Releases

### ISSUE THREAD

**Issue by mathmaniac43** [bonukai/MediaTracker#210]
It would be helpful to have [Semantically-versioned tags](https://semver.org/) on the code in the repository, as well as uniquely versioned DockerHub images. This allows repeatability, and makes it easy for folks to upgrade or downgrade from one version to another to keep things working.

This project seems to be under pretty rapid development (which is great!), so maybe it is a bit early to start SemVer-tagged releases on both GitHub and Dockerhub (though I would encourage it!). However, it would be a good compromise to add some date-time-taged images along with `latest` in Dockerhub to achieve a similar result. I will try to put together a MR to the GitHub workflow to add this as an initial capability; please let me know what you think.

Thanks!

**Comment by CountMurphy** [comment]
I maintain an unofficial Arch AUR package for mediatracker. Tagged releases would very much make my life  a bit easier (updating the package once per release vs once per commit).

**Comment by bonukai** [comment]
I will start making releases with SemVer on GitHub.

What would be the best option for tagging Docker images. For now, I will be probably realising new version every week, but I would also like to push image to Docker Hub with every commit, like now, is this a good practice?

So images for releases would be tagged with SemVer, and those for every commit with something like `unstable-{timestamp}`

**Comment by mathmaniac43** [comment]
That sounds like a great compromise @bonukai , makes it easy for folks to stay on the bleeding edge with you or pick what you consider more complete/stable branches. Let me know if you need any help coordinating that, but I think you have it figured out!

**Comment by bonukai** [comment]
So, I decided to only use tagged releases, Docker images won't be pushed with every commit, instead I will use GitHub `pre-release` feature. However, I'am not sure how to tag those releases, should `latest` include `pre-release` version?

**Comment by mathmaniac43** [comment]
@bonukai I think that typically `latest` implies that it is also a "stable" release, so personally I would float that along with the most recent full release version. Maybe a better one for the pre-release versions would be `experimental` or `unstable` or `bleeding-edge`? I think you will be able to "get away" however you personally prefer; I just recommend documenting what each means once you decide!

**Comment by bonukai** [comment]
@mathmaniac43 Thank you, I set up GitHub actions, and used your suggestions for tagging images.

**Comment by mathmaniac43** [comment]
Thanks for your hard work and being flexible! Hope I can help out a bit in the future. =)
