### ISSUE TITLE
[Bug] Unable to access the home page

### ISSUE THREAD

**Issue by SirBogner** [bonukai/MediaTracker#213]
After the update adding the stats, I'm not able to access the front page/home page of my instance. The page goes totally blank without buttons or any text. I still am able to access the "tv", "movies" and so on, if I firstly of all specify the right url and clear cache. 
I've tried creating a new .db-file, updating to the latest docker image and of cause restarting the container. 

My latest log tells me nothing out of the ordinary - right?

```
4.3.2022 14.37.45 info: Updating: The Book of Boba Fett (last updated at: 3/4/2022, 1:37:35 PM)
4.3.2022 14.37.36 info: Updated 1 item
4.3.2022 14.37.35 info: Updating: The Book of Boba Fett (last updated at: 2/15/2022, 2:01:44 PM)
4.3.2022 14.37.35 info: Updating metadata for 50 items
4.3.2022 14.37.34 info: MediaTracker listening at http://mediatracker:7481
4.3.2022 14.37.27 info: Modtaget signal SIGTERM
```

**Comment by CountMurphy** [comment]
Same issue here. Lots of javascript bugs in the console: 

```javascript
TypeError: e.movie is undefined
Uncaught TypeError: e.movie is undefined
```

**Comment by bonukai** [comment]
I can't test it right now, but I think I've fixed it

**Comment by CountMurphy** [comment]
I'll rebuild and let you know :)

**Comment by SirBogner** [comment]
Great! It works at my end

**Comment by CountMurphy** [comment]
Confirmed on my end too
