### ISSUE TITLE
Watched episodes

### ISSUE THREAD

**Issue by FedorAdo** [bonukai/MediaTracker#227]
Hi! Can this be fixed somehow?

![1](https://user-images.githubusercontent.com/30267668/157913016-0c8e9c0b-e74f-46bf-a46c-a7dae6a0d3d0.jpg)
![2](https://user-images.githubusercontent.com/30267668/157913009-954edf79-7949-4897-8537-ec22db18c3bb.jpg)

**Comment by SirBogner** [comment]
Have you tried clearing site cache?

**Comment by bonukai** [comment]
I can't replicate this bug, it was fixed before. Are you using latest version 0.0.6, what is your browser?

Older version of the client could be cached be your web browser, refreshing page should help, if that's the issue, like @SirBogner suggested

**Comment by FedorAdo** [comment]
Clearing cache doesn't help. Ran a docker container (latest and unstable) on two different servers.
When starting a container, the portainer writes 
`<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web site created using create-react-app"/><title>Media Tracker</title><script>if ( localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches) ) { document.documentElement.classList.add('dark'); } else { document.documentElement.classList.remove('dark'); }</script><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"/><link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet"/><script defer="defer" src="main_ac703d6f.js"></script><link href="main_ac703d6f.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><div id="portal"></div><div id="modals"></div></body></html> 100 1211 100 1211 0 0 32185 0 --:--:-- --:--:-- --:--:-- 32729`
I don't know if this is relevant or not. And in the logs, except for the info 
```
12.03.2022, 13:01:15 info: Everything up to date
12.03.2022, 13:01:15 info: Updating metadata for 2 items
12.03.2022, 13:01:15 info: MediaTracker listening at http://2c5776fcaa9f:7481
```
 and http section, there is nothing.
Interestingly, the same thing happens on https://mediatracker-bonukai.herokuapp.com (demo demo). 
 From three different computers (windows 10), from different browsers, clearing the cache every time, through a virtual machine, installing windows 10 and Google Chrome cleanly and even try several VPN.

**Comment by bonukai** [comment]
@FedorAdo  Could you try version 0.0.7

**Comment by FedorAdo** [comment]
![3](https://user-images.githubusercontent.com/30267668/158056014-cef2b23a-fad0-4ebd-a8f5-a41c373c65b0.jpg)
![4](https://user-images.githubusercontent.com/30267668/158056016-fc86cff4-1ad5-40fd-936d-4c091c79b5b2.jpg)
Oh, thank you very much!
0.0.7 immediately started up as it should.
