### ISSUE TITLE
[Bug] Unable to log in using 0.0.7

### ISSUE THREAD

**Issue by SirBogner** [bonukai/MediaTracker#232]
The last update made it impossible for me to log in using my old database - giving me the error code shown in the image below. 
Creating a new database seems to fix the issue, although I havn't tested if it would occur again after adding shows ect. to the watchlist.

![image](https://user-images.githubusercontent.com/83633524/158074975-6cefc56c-4e35-43aa-b3d0-58365d360a7b.png)

**Comment by bonukai** [comment]
Migration is failing, I can't figure out why. Could you show the rest of the logs from line starting with:
```
    at client.transaction.connection (/app/node_modules/knex/lib/...
```

**Comment by SirBogner** [comment]
Sure. Here you go:
{"id":"WEBL9eBy7WFfpdcBi6iYxHjJnSmMeu6mrGvR","level":"error","message":"FOREIGN KEY constraint failed","stack":"Error: FOREIGN KEY constraint failed\n    at client.transaction.connection (/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:359:21)","timestamp":"2022-03-14T19:38:11.819Z"}
{"id":"pIsJbvCeOeRQuKWPuPruTjpnj-H7AD7rvb9i","level":"info","message":"MediaTracker listening at http://mediatracker:7481","timestamp":"2022-03-14T19:38:11.860Z"}
{"id":"83uBSTwUd5Sany3nEk_fIcM7jZfVNUv8ftE6","level":"info","message":"Updating metadata for 48 items","timestamp":"2022-03-14T19:38:11.963Z"}
{"id":"-MUplvqf0V_6Es4GvQKW66i1l6kmit69VlKJ","level":"info","message":"Everything up to date","timestamp":"2022-03-14T19:38:11.965Z"}
{"id":"JyyleVRLgV9bPEUAFTvkFvCnFP3HnDGR5eD3","level":"error","message":"select `id`, `name`, `slug`, `admin`, `publicReviews`, `sendNotificationWhenStatusChanges`, `sendNotificationWhenReleaseDateChanges`, `sendNotificationWhenNumberOfSeasonsChanges`, `sendNotificationForReleases`, `sendNotificationForEpisodesReleases`, `notificationPlatform`, `hideOverviewForUnseenSeasons`, `hideEpisodeTitleForUnseenEpisodes` from `user` where `id` = 1 limit 1 - no such column: slug","stack":"SqliteError: select `id`, `name`, `slug`, `admin`, `publicReviews`, `sendNotificationWhenStatusChanges`, `sendNotificationWhenReleaseDateChanges`, `sendNotificationWhenNumberOfSeasonsChanges`, `sendNotificationForReleases`, `sendNotificationForEpisodesReleases`, `notificationPlatform`, `hideOverviewForUnseenSeasons`, `hideEpisodeTitleForUnseenEpisodes` from `user` where `id` = 1 limit 1 - no such column: slug\n    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)\n    at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)\n    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)\n    at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)\n    at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)\n    at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)\n    at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)\n    at Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)\n    at UserRepository.findOne (/app/src/repository/user.ts:36:18)\n    at Array.<anonymous> (/app/src/controllers/users.ts:33:20)","timestamp":"2022-03-14T19:46:12.739Z"}

**Comment by bonukai** [comment]
After hours of debugging, and filling database with random data, I still can't replicate this error, migration passes on my system, as do all tests.

I updated migration, but I don't know if it will work for you, but you can try version 0.0.8

**Comment by SirBogner** [comment]
No worries. Thank you for putting in hard work! 
After updating to 0.0.8 I couldn't even access MediaTracker - meaning not even ending up at the "loading" page. I ended up creating a new database, which seemed to fix the issues. I will of couse let you know if the problem returns in the future.
