### ISSUE TITLE
Edit entries in Play/Watch History

### ISSUE THREAD

**Issue by Mintww** [bonukai/MediaTracker#266]
Is there a way you can add the ability to remove or edit specific instances in the Play/Watch/Read/etc. history?
I've managed to set a play of a video game 6 months into the future instead of 6 months in the past by entering the wrong year on the date. It's a game I have several plays of that I don't want to have to re-enter by hand, so I'd appreciate being able to edit just the one mistaken entry. (It also may be good to sanity check that you can't future date these things, but I don't think that's super important.)

**Comment by bonukai** [comment]
You can now remove specific watch history entry from seen history page, and future date is validated both un UI and on the serwer side. Thank you for your input :)

You can try it out in `bonukai/mediatracker:0.1.0-beta6`

**Comment by Mintww** [comment]
There's buttons under each entry, but clicking one asks me if I want to remove all of them... and indeed, removed all of them.

**Comment by bonukai** [comment]
I don't know what I was thinking implementing this :)

It should work correctly in version `0.1.0-beta.13`

**Comment by Mintww** [comment]
Yep, seems to be working now, thank you!
