### ISSUE TITLE
Allow marking media without a release date as seen

### ISSUE THREAD

**Issue by Mintww** [bonukai/MediaTracker#326]
Some less popular media exists in the databases used but doesn't have a release date in said database despite having already been released. It would be nice to be able to mark these as seen regardless.

**Comment by bonukai** [comment]
Thank you, I didn't think of situation like this. This should be enabled in version `0.1.0-beta.13`

**Comment by Mintww** [comment]
Oops, forgot to get back to you on this. It seems to be working, thank you!
