### ISSUE TITLE
API /calendar date format

### ISSUE THREAD

**Issue by Fabaderheld** [bonukai/MediaTracker#337]
Hy,

as the title stated I wasn't able to get anything from the api /calendar due to using the wrong format. I didn't find anything on which format is the correct one.

thanks
Fabian

**Comment by bonukai** [comment]
Date string should be in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, I updated documentation to include this. Thank you

**Comment by Fabaderheld** [comment]
Yeah, I thought I already tried it, but seems not. Anyways it is working as described.

Thanks

Faba
