### ISSUE TITLE
Trakt.tv import doesn't import much info

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#338]
Hi, finally with Lists added I started from scratch and tried to import my Trakt.tv info, but it seems that it doesn't import much info:

EDIT: 

Peliculas = Movies
Programas = Shows
Temporadas = Seasons
Episodios = Episodes
Lista de seguimiento = Watchlist
Historial de visionado = Seen history
Puntuaciones = Scores

![image](https://user-images.githubusercontent.com/11770760/167834366-7acbc229-e990-474d-8011-437bd033e8d7.png)

It doesn't import any episode watched nor any movie watched, while my trakt.tv profile has 2 pages of series progress and 678 movies watched:

![image](https://user-images.githubusercontent.com/11770760/167833162-6ac6f4a8-8719-4cf0-894f-7f26d5e79748.png)
![image](https://user-images.githubusercontent.com/11770760/167833285-b7145b7a-e1c5-4695-80c9-84a6d98c5c73.png)

In the logs I don't see anything relevant.

I'm using the last commit of the repository manually compiled, but after that I also tried with npm install -g mediatracker and in that version it has the same result.

**Comment by BanCrash** [comment]
I've saw in the Trakt.tv api that they send the information in pages, could be that MediaTracker is only reading the first page? I see that there are a few episodes and movies added as watched, and I checked my history and all the stuff before May 3 is not added, but all after May 3 included until yesterday (when I did the import) is added.

So I think the issue could be that is only reading the first page?

**Comment by bonukai** [comment]
Thank you. Pagination is optional for watchlist and ratings, so I incorrectly assumed it's also optional for history, now I see it's not

**Comment by JourneyOver** [comment]
not sure what exactly is going on with mine, as it's barely importing anything at all from trakt.. A couple things are just stuck at ?/{number} .. ontop of it not really importing fully or at all :/

![05-28-2022_11-36-22](https://user-images.githubusercontent.com/13910285/170834586-85495d4f-e61c-4a9e-aec5-0abe81f6abe3.png)
![05-28-2022_11-35-58](https://user-images.githubusercontent.com/13910285/170834587-8d707820-8d6f-4777-8bec-95d621fafe70.png)

This is running from source. I let it sit for a while in hopes that maybe it was still just importing, but nothing ever changed.

**Comment by Ardakilic** [comment]
Hello, can confirm mine only gets 6 tv shows as well, and not much else.

**Comment by blackph0en1x** [comment]
Hi,
I am having problems importing from trakt too. I have a some personal list and nothing on my watchlist list and, of course, a bunch of watched movies/episodes.
When I try import from trakt I am able to successfully authenticate with trakt but then I am stuck on the importing page witch briefly states "exporting" to turn nearly immediately to "importing" without any other progress and no import ever happening.
<img width="1203" alt="Screenshot 2022-10-31 alle 14 45 23" src="https://user-images.githubusercontent.com/39968575/199023030-36ee09a8-f67a-4c78-866f-da5abcb40a50.png">

**Comment by BanCrash** [comment]
Hi @bonukai , did you get any progress on this matter? After the data lose I would like to get all the info I can from Trakt to be sure that all these years of stats don't get lost.

**Comment by bonukai** [comment]
I started working on that long time ago, it only needs some tests, I will try to finish it soon. I wish I could have more time to work on this project

**Comment by BanCrash** [comment]
> I started working on that long time ago, it only needs some tests, I will try to finish it soon. I wish I could have more time to work on this project

Sure, I understand that. Thanks for the update!

**Comment by Buddinski88** [comment]
@bonukai it is the same behavior with me. Only the contents of the watchlist are imported.

Thank you at this point for your efforts! I really appreciate it.

Can you tell when to test the revised import?

**Comment by phirestalker** [comment]
I am literally sick of Trakt. I mark things watched and later they don't show as watched.
I looked into the code, but I wouldn't know how to make the tests. I might be able to cobble the functionaility together, but you said you got that done already. Is there any way that I can help? Make some fake data file or something?

**Comment by bonukai** [comment]
@phirestalker I've just published all the changes I was working on to a branch `wip`, including TraktTv import. There are few big changes there, if you could test it manually, that would be very helpful.

**Comment by BanCrash** [comment]
It seems that with that version its importing more info, but I have to execute several times the import to have all the media:

Second time of importing the same account (the first time I didn't made a screenshot, but it imported less items):
![imagen](https://user-images.githubusercontent.com/11770760/233774348-e496d8f2-6a2c-40d6-81d2-9c0f8e40bbec.png)

Third time:
![imagen](https://user-images.githubusercontent.com/11770760/233774463-b137cefa-7b50-4dd1-a6f9-cab96d7a968b.png)

Fourth time:
![imagen](https://user-images.githubusercontent.com/11770760/233774549-d40ca202-d242-421e-b776-4e65e8e7b2c7.png)

etc.

As you can see, on each import the quantity gets higher but never reach the maximum (for example, "Episodios" (Episodes) started on 1523 on the second import, and in the 4th reached 3603, but didn't reach the 6891 items that are on my trakt profile).

**Comment by BanCrash** [comment]
@bonukai I've found these little issues (the one on this issue and #488 & #489 ), but in general I'm really happy with this update, great job!

**Comment by phirestalker** [comment]
Fired up a docker from that branch. How do I know it is doing something? The numbers are not changing, but it says importing for the past 5 minutes.

**Comment by phirestalker** [comment]
I did the first one wrong. I had to edit the docker-compose.yaml to use the local Dockerfile. I see the same behavior as @BanCrash.
git show
```
git show
commit 99207bedd77a722d5056b607569dfa0ff7c5650f (HEAD -> wip, origin/wip)
Author: bonukai <17750886+bonukai@users.noreply.github.com>
Date:   Sat Apr 22 15:27:25 2023 +0100
```

**Comment by bonukai** [comment]
@phirestalker Could you please try again, I have just added some changes

**Comment by phirestalker** [comment]
I noticed it kept what it had before. Should I delete the db when I try again? If so, where can I find it?

**Comment by bonukai** [comment]
You can use the same database, importing items again will add only those items that are not in your database

**Comment by phirestalker** [comment]
It almost imported everything on the first try. The second try it gave an error.
### First time
<img width="1098" alt="Screenshot 2023-04-22 at 5 41 08 PM" src="https://user-images.githubusercontent.com/7477095/233813424-cc4044cd-7791-4b16-8589-cfd759a1b4a5.png">

### Second time
<img width="1108" alt="Screenshot 2023-04-22 at 5 42 41 PM" src="https://user-images.githubusercontent.com/7477095/233813445-9f290313-7976-46ff-b1d5-742027c754d5.png">

**Comment by bonukai** [comment]
@phirestalker this issue should be solved now

**Comment by bonukai** [comment]
@BanCrash I've updated the how metadata is downloaded and this should fix the problem you are experiencing here, where you need to run the import multiple times

**Comment by bonukai** [comment]
Now if item is not found by tmdb id it will also be search by imdb id, maybe this will help to import all items

**Comment by BanCrash** [comment]
Hi again @bonukai , I used the import on my previous database and it imported everything, but then for more testing I deleted the database and tried to import and I got this huge error: (I put in a .txt because it's so big)

[Error.txt](https://github.com/bonukai/MediaTracker/files/11303059/Error.txt)

**Comment by bonukai** [comment]
@BanCrash I forgot there is a limit to how many records can be inserted at once, it should be fixed now, thank you.

**Comment by phirestalker** [comment]
I tried with the new updates. I did not delete my database, seeing if it would fill in the missing ones. I got an error that I have attached here.
[MediaTracker error.txt](https://github.com/bonukai/MediaTracker/files/11303813/MediaTracker.error.txt)

**Comment by BanCrash** [comment]
> @BanCrash I forgot there is a limit to how many records can be inserted at once, it should be fixed now, thank you.

@bonukai Ok, now on the first attempt after deleting the database I got this:

![imagen](https://user-images.githubusercontent.com/11770760/233841272-9a9c33df-e8da-4430-889b-3604c5f37274.png)

Importing again doesn't have any change so it seems that this is the maximum I'm gonna get. Another suggestion arrives then, could you add to the log the items that are missing?

Debugging myself I achieve to print to the console four items:
Test1: Trakt 411426 Slug: vader-episode-i-2018
Tmbd: 560927
Test1: Trakt 185335 Slug: shrek-3d-the-story-continues-2003
Tmbd: 288306
Test1: Trakt 72222 Slug: huerfanos-electronicos
IMDB: tt3317336
Test1: Trakt 109068 Slug: overwatch
IMBD tt4332152

But there are a lot more missing and I don't know how to continue.

In any case thank you for taking time fixing this!

**Comment by bonukai** [comment]
@phirestalker this have been now fixed.

@BanCrash Now after importing all not imported items will be displayed on the page. It looks like they are not in TMDb database and TMDb ids on Trakt are invalid for those items

**Comment by BanCrash** [comment]
> @phirestalker this have been now fixed.
> 
> @BanCrash Now after importing all not imported items will be displayed on the page. It looks like they are not in TMDb database and TMDb ids on Trakt are invalid for those items

Just tested and it works like a charm, thanks!

For my side I think this issue can be closed, let's see what @phirestalker say.

**Comment by phirestalker** [comment]
I love it!
Quick question. For upcoming titles that are missing on TMDB, does it use the IMDB id and keep it?
Thank you for working on this.

**Comment by bonukai** [comment]
No, the items the are not on the IMDb are simply omitted. After looking at some examples, I think this is the best solution.

For example [Vader- Episode I](https://trakt.tv/movies/vader-episode-i-2018) has invalid [TMDb id](https://www.themoviedb.org/movie/560927), just like [Shrek +3D - The Story Continues](https://trakt.tv/movies/shrek-3d-the-story-continues-2003). A [Overwatch shows](https://trakt.tv/shows/overwatch) links to [Overwatch game](https://www.imdb.com/title/tt4332152/) on IMDB, there are two separate entries for the same Tv Show [Divorce](https://trakt.tv/shows/divorce-2016) and [Divorce](https://trakt.tv/shows/divorce-hbo).

I think it's better to keep only TMDb as the only source

**Comment by phirestalker** [comment]
sounds right. Thanks again.

**Comment by BanCrash** [comment]
In any case when #56 is added we well be added to manually fix that so not a big issue. Closing this since it's already solved, thanks!
