### ISSUE TITLE
armv7 docker image for Raspberry Pi

### ISSUE THREAD

**Issue by BinaryGenius** [bonukai/MediaTracker#351]
I run most of my services on a raspberry pi 4B and this service is **exactly** what I've been looking for. I have a tracker for anime, games, books, & shows/movies maybe music soon. The issue with my setup is I want the media trackers so to speak, to be offline/self hosted & all in one service. I have no knowledge of how to import a docker image to different architecture and would greatly appreciate an armv7 image. I'm open to help with the project if anyone could give me some pointers.

**Comment by bonukai** [comment]
I added docker image for arm64, it didn't required any changes, I believe it should be working on [Raspberry Pi 4 Model B](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/specifications/).

As for armv7, Dockerfile will need some changes to install [sharp](https://sharp.pixelplumbing.com/install), as it requires [libvips v8.12.2](https://github.com/lovell/sharp/blob/04c31b35a7e2d88931e1cb7cde0fe1720e4685b7/package.json#L157), but vips on alpine v3.15 (latest stable version used by node:17-alpine) has version [8.12.1](https://pkgs.alpinelinux.org/package/v3.15/community/armv7/vips).

I was able to compile libvips from source, and install sharp, but I don't know how to copy installed libvips, to keep Dokcer image size small

```Dockerfile
FROM node:17-alpine as libvips

WORKDIR /libvips
RUN apk add --no-cache wget g++ make expat-dev glib-dev python3 libwebp-dev jpeg-dev fftw-dev orc-dev libpng-dev tiff-dev lcms2-dev librsvg-dev libheif-dev
RUN wget https://github.com/libvips/libvips/releases/download/v8.12.2/vips-8.12.2.tar.gz
RUN tar xf vips-8.12.2.tar.gz
WORKDIR /libvips/vips-8.12.2
RUN ./configure
RUN make
RUN make install

FROM node:17-alpine
# TODO: copy libvips
RUN apk add python3 g++ make 
WORKDIR /app
RUN npm i sharp
```

This can be tested with `docker buildx build . --platform linux/arm/v7`

**Comment by BinaryGenius** [comment]
Sorry but I tried to read this yesterday and I'm worried I'll break something since I'm new to this. From what I'm gathering I need to separately install something called sharp and version 8.12.2 of libvips. Then I need to copy whatever you typed into a Dockerfile which I don't know how to name and then run this command `docker buildx build . --platform linux/arm/v7`? Docker is just docker I don't know what buildx is maybe "x" is a variable it looks like build is support to build the image from Dockerfile the "." is for current dir I know that. And the --platform argument is presumably needed to specify this is an arm image since this image was previously used on a different architecture.

**Comment by BinaryGenius** [comment]
```
Unable to find image 'bonukai/mediatracker:0.1.0-beta.17' locally
0.1.0-beta.17: Pulling from bonukai/mediatracker
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
```
I also tried copying your text and pasting into a Dockerfile I believe that is a Dockerfile but you just pasted its contents I tried to build but it seems like I need to compile libvips and sharp from source and/or do some weird stuff because nothing seems to be ready made for raspberry pi hooray. Thought I'd write back instead of mindlessly working through the problem on my own maybe you could quickly solve this since I'm uneducated about this.

**Comment by bonukai** [comment]
`alpine 3.16` is now available, with [vips 8.12.2-r5](https://pkgs.alpinelinux.org/package/v3.16/community/armv7/vips), minimum required version by `sharp`. I already tested it on `armv7` and it works, but I will wait until `node17:alpine3.16` is released, hopefully it won't take long, then making Dockerfile to support `armv7` will require only few small changes

**Comment by BinaryGenius** [comment]
Alright I guess we'll wait till then.

**Comment by mobiuscreek** [comment]
Thank you for your hard work @bonukai. Version [bonukai/mediatracker:0.1.0-beta.19](https://hub.docker.com/layers/mediatracker/bonukai/mediatracker/0.1.0-beta.19/images/sha256-c5f96e61eb6a6e753a5ef412fc2e00014088e7b776ae3e885d56b3a90bafe3fe?context=explore) on an RPi 4 Model B Rev 1.1 works perfectly. I guess this issue should clarify that it's specifically for `armv7` architectures.

**Comment by BinaryGenius** [comment]
Personally I like my longer name so it makes it easier for users to search the issues but it is what it is. I'll report back to see if it works on my pi as well.

**Comment by bonukai** [comment]
@BinaryGenius I didn't made any changes to this since `0.1.0-beta.17`, that you tried before, so probably your Raspberry Pi has `armv7` and it still won't work, but in the meantime you could try to use npm version with 
```
npm install -g mediatracker
mediatracker
```

**Comment by BinaryGenius** [comment]
I'm confused why @mobiuscreek said it did work on armv7 because it doesn't work for me you are correct. If that wait isn't too long I'll wait till there is a working docker image because I like to have everything portable and isolated.

**Comment by bonukai** [comment]
His Raspberry Pi is `armv8`, yours is `armv7`

We have to wait for this pull request to be merged https://github.com/nodejs/docker-node/pull/1729

**Comment by BinaryGenius** [comment]
Oh must be a newer raspberry pi 4 I bought mine before the prices shot up so I didn't expect anyone to still be buying. I can wait until it gets merged but if you have any new information about the armv7 docker image just reply to me so I can be notified in my email and test out the new image.

**Comment by mobiuscreek** [comment]
@BinaryGenius, sorry for the confusion. You can verify your machine's hardware name by typing `uname -m` in the command line. For example you might get `aarch64` (for an `armv8` CPU) which is a 64bit system or `armv7l` for a 32bit system. In the Raspberry Pi 4B I tried it prints out the former.

**Comment by bonukai** [comment]
@BinaryGenius Could you try version `bonukai/mediatracker:0.1.0-beta.21`, it should support `armv7`, please test if posters are showing in the search results

**Comment by BinaryGenius** [comment]
Oh damn armv7l is 32bit? That's what I have. I used the docker compose and supplanted the regular image with the beta image and it works flawlessly. Hopefully more people can test this to make sure it's stable because this would be an amazing addition to things like jellyfin and jellyseer. I've attached some images below if there is anything else you want me to test I'm all ears. Otherwise thanks for the hard work you've put in, from what I've seen this service is going to be an excellent addition to my life _and a private one too_.
![Screenshot from 2022-06-08 01-47-18](https://user-images.githubusercontent.com/105467963/172541587-26410e5d-b332-4997-8cf1-8f143ef5e241.png)
![Screenshot from 2022-06-08 01-47-03](https://user-images.githubusercontent.com/105467963/172541589-026ef1a2-66fa-4f3a-b152-cdd47f535587.png)
![Screenshot from 2022-06-08 01-46-58](https://user-images.githubusercontent.com/105467963/172541590-f30e38f3-10c8-4d55-8746-bec4e110fc57.png)
![Screenshot from 2022-06-08 01-46-40](https://user-images.githubusercontent.com/105467963/172541591-b02658a7-1d1e-447e-a502-8f7d636196e3.png)
![Screenshot from 2022-06-08 01-46-29](https://user-images.githubusercontent.com/105467963/172541594-83a1bed4-31c8-44f0-a4a5-c2f04862a6d1.png)

**Comment by BinaryGenius** [comment]
Sorry should we close this issue I just want to make sure it's solved and there hasn't been any response in 2 weeks.

**Comment by bonukai** [comment]
For games you need to set your own IGDB api key, because of the limits 

> IGDB has a limit of 4 requests per second. Because of that IGDB API key is not provided with MediaTracker, it can be acquired [here](https://api-docs.igdb.com/#account-creation) and set in http://localhost:7481/#/settings/configuration
