### ISSUE TITLE
Add to Seen History Date is One Day Behind Selection

### ISSUE THREAD

**Issue by mathmaniac43** [bonukai/MediaTracker#364]
Hello,

I am accessing MediaTracker 0.1.0-beta16 on my Android phone. When I go to add a movie to my watch history, the date/time pickers are initially set to the correct current date and time. However, if I go to select a prior date, the date it actually sets in the box is always one day earlier. For example, I selected 2022-05-20, but the box changed to 2022-05-19 instead. In order to get the box to the correct date, I had to pick the day after the one I actually wanted.

Thanks.

**Comment by bonukai** [comment]
It's similar bug like in #261, I missed this one place, it should be new fixed in version `0.1.0-beta.17`

**Comment by mathmaniac43** [comment]
Tested the new release, that worked for me, thank you!
