### ISSUE TITLE
Version Information

### ISSUE THREAD

**Issue by samcro1967** [bonukai/MediaTracker#375]
Is there any place I am missing in the GUI that show the current version I am running?

**Comment by Calorian** [comment]
Settings (username, top right) > About
Though I've noted I'm running the Beta 17 container but the page says 16 still.

**Comment by samcro1967** [comment]
I do not see settings in the upper right hand corner.  I only see my username.  When I click on it, I do not see an about tab in the menu.  I am running bonukai/mediatracker from Docker Hub.  I see there is an unstable tag on Docker Hub that is only a few days old.  Latest is 2 months old.  It must have been added more recently and has not made it to the latest version yet.

**Comment by bonukai** [comment]
Yes, it's only on the `unstable`, and it shows previous version instead current one (it's a bug)

**Comment by Quentin-ctrL** [comment]
Hi,

Is this still open ?
I checked and found the version in the about section.

ex: https://mediatracker.me.xyz/#/settings/about

> About
> Version: 0.2.2
