### ISSUE TITLE
What about: Other languages then english and more detailed games tracking

### ISSUE THREAD

**Issue by URBANsUNITED** [bonukai/MediaTracker#4]
Hi!
Is there any chance to support other languages like German maybe? 
TMDB has German support. Maybe by using the API key???

And any chance by having game progress support?
Like GameTrack
https://gametrack.app/
or Games Tracker
https://gamestracking.com/

Thanks

**Comment by bonukai** [comment]
Support for other languages is coming soon.

I think I will also add progress in the future

**Comment by bonukai** [comment]
@URBANsUNITED 

You can now configure TMDB and audible to use German language. Add following environment variables:
```
TMDB_LANG=de
AUDIBLE_LANG=de
``` 
and all search results from those two services will be in German. Existing metadata will be gradually updated over time, at this moment you can't force update for entire database.

Unfortunately IGDB is only available in English

**Comment by URBANsUNITED** [comment]
Hi!

Thanks for the new options. Unfortunately it doesn't work.
Pulled the latest docker with the new variables, but still english.

BTW.
Any chance for multi language dashboard?
I could translate the english to german part if you like.

Thanks

URBANsUNITED

**Comment by bonukai** [comment]
> Thanks for the new options. Unfortunately it doesn't work.

Could you try to search for something that you never search before? All search results are saved in local database, when you search again for the same thing, those results are pulled from this database.

> Any chance for multi language dashboard?

I will start working on that after I figure out while some tests are sometimes failing :)

**Comment by bonukai** [comment]
I added full support for localization, you can add translations here: [https://crwd.in/mediatracker](https://crwd.in/mediatracker).

Language in web browser should be detected automatically, on server side it can be set by environment variable `LANG`

**Comment by URBANsUNITED** [comment]
Hi!
Finished lots of entries already :)
Here is a typo:
/MediaTracker / main/server/src/i18n/locale/en/Serwer 
Serwer = Server
and these:
![Bildschirmfoto 2022-01-28 um 07 55 30](https://user-images.githubusercontent.com/6212300/151501506-38773559-fd57-4467-a125-cbdb0c876858.png)
wont = want

I will update the other later and when the translation is available I will check against in the dashboard

**Comment by URBANsUNITED** [comment]
So, finished all translations for now. Maybe I will change some again. You know you need to see it and the context ;)

Here is the : missing for Authors
![Bildschirmfoto 2022-01-29 um 14 36 33](https://user-images.githubusercontent.com/6212300/151663187-9a8df262-c456-4db7-9cda-764fb8ee7df4.png)

And I personally don't like the two big lables. The former ones were smaller. Here you barely can see the cover now:
![Bildschirmfoto 2022-01-29 um 14 36 22](https://user-images.githubusercontent.com/6212300/151663206-0afe7fe2-af9c-470e-9800-862852c9832e.png)

Cheers

URBANsUNITED

**Comment by bonukai** [comment]
Thank you so much. I rally appreciate your feedback, if you have any feature request, please feel free to open an issue.

For now I moved those buttons below poster, they are only visible on search.
