### ISSUE TITLE
Fonts issue

### ISSUE THREAD

**Issue by Quentin-ctrL** [bonukai/MediaTracker#400]
Hello,

I have a pb with the icons, on my browser they're missing on the demo and local (using docker-compose)
- http://localhost:7481/#/
- https://mediatracker-bonukai.herokuapp.com/#/

example: 'mode_night' > icon missing
![image](https://user-images.githubusercontent.com/70467477/173191021-5298e857-ee26-4402-8d83-acaaa7aed937.png)

Not working on : Mozilla Firefox 91.10.0esr

Self hosted service do no need external dependencies. 
Can you add icons font ?

edit: I fix my issue changing my FF settings 
[X] Allow pages to choose their own fonts, instead of your selections above.
cf. https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use

**Comment by bonukai** [comment]
From version `mediatracker:0.1.0-beta.29` all fonts are local
