### ISSUE TITLE
TV Episode Release Alerts Show Up 12 hours Prior To Actual Release 

### ISSUE THREAD

**Issue by gabeanelson** [bonukai/MediaTracker#418]
Is there something I need with Time Zones in the docker or a trick to getting alerts when shows are actually released? I’m based in the Los Angeles time zone, and I always receive alerts 12 hours before their actual release date.

**Comment by bonukai** [comment]
You can add environment variable to Docker with your time zone: `TZ=America/Los_Angeles`. I updated README to include this information and from version `0.1.0-beta.30` server will log time zone and current time on start and scheduled notifications

**Comment by bonukai** [comment]
Actually there is also a bug with time zones there, I am writing tests for the fix now

**Comment by bonukai** [comment]
It's now fixed in version `0.1.0-beta.32`. Notifications for release dates will be send at midnight in local time set with `TZ`
