### ISSUE TITLE
Can't fetch Games: Server error 500 (Internal Server Error)

### ISSUE THREAD

**Issue by zero-thermo** [bonukai/MediaTracker#435]
Installed via docker-compose as suggested.

All other categories seem to work fine and produce search results, except for Gaming. When searching for a game, MediaTracker stays on loading until eventually showing a red "Server error 500 (Internal Server Error)"

Logs show errors like this:
```
error: Error: Request failed with status code 400
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1342:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Bug? What else can I do to help troubleshoot?

Thanks for creating this much needed open-source, self-hosted alternative.

**Comment by BanCrash** [comment]
Hi, did you set up the IGDB api key?

From the readme:
* IGDB has a limit of 4 requests per second. Because of that IGDB API key is not provided with MediaTracker, it can be acquired [here](https://api-docs.igdb.com/#account-creation) and set in http://localhost:7481/#/settings/configuration

**Comment by zero-thermo** [comment]
That was it! Appreciate you pointing that out. I wasn't able to retrieve an IGDB access token, but somehow Game search now works with just the Twitch client ID and secret entered into MediaTracker.

After following the [IGDB docs](https://api-docs.igdb.com/#account-creation), I couldn't figure out the `POST` request to get a bearer access token.

I ran the following command from the MediaTracker server host with my Twitch secret and credentials:
```
POST https://id.twitch.tv/oauth2/token?client_id=abcdefg12345&client_secret=hijklmn67890&grant_type=client_credentials
```

It produced the following instead of the access token:
```
[5] 2677677
[6] 2677678
user@server:/mediatracker$ Please enter content (application/x-www-form-urlencoded) to be POSTed:
```

What am I supposed to enter?

However, after entering my Twitch client ID and secret in the [MediaTracker IDGB credentials section](http://localhost:7481/#/settings/configuration), Game search now works. How is this possible without the access token?

**Comment by BanCrash** [comment]
> That was it! Appreciate you pointing that out. I wasn't able to retrieve an IGDB access token, but somehow Game search now works with just the Twitch client ID and secret entered into MediaTracker.
> 
> After following the [IGDB docs](https://api-docs.igdb.com/#account-creation), I couldn't figure out the `POST` request to get a bearer access token.
> 
> I ran the following command from the MediaTracker server host with my Twitch secret and credentials:
> 
> ```
> POST https://id.twitch.tv/oauth2/token?client_id=abcdefg12345&client_secret=hijklmn67890&grant_type=client_credentials
> ```
> 
> It produced the following instead of the access token:
> 
> ```
> [5] 2677677
> [6] 2677678
> user@server:/mediatracker$ Please enter content (application/x-www-form-urlencoded) to be POSTed:
> ```
> 
> What am I supposed to enter?
> 
> Despite not having an IGDB token, I entered my Twitch client ID and secret in the [MediaTracker IGDB credentials section](http://localhost:7481/#/settings/configuration), and Game search now works. How is this possible without the access token?

Well, I don't know anything about that tbh, maybe @bonukai could help.

**Comment by bonukai** [comment]
All you need is Client Secret and Client ID, you don't need to do anything else.
