### ISSUE TITLE
IMDB TV Show Season/Episode Missing

### ISSUE THREAD

**Issue by mathmaniac43** [bonukai/MediaTracker#437]
I noticed that the show The IT Crowd is missing Season 5 in MediaTracker. This is a bit of an odd case because there is only one episode, and it comes up as Episode 0. I wonder if there is logic in MediaTracker that assumes episodes start at 1, which causes Episode 0 to get skipped.

https://m.imdb.com/title/tt0487831/episodes/?season=5

**Comment by bonukai** [comment]
Metadata for Tv shows is downloaded from [TMDB](https://www.themoviedb.org/tv/2490-the-it-crowd/seasons). This one episode from season 5 from imdb is in a `Specials` season on TMDB
