### ISSUE TITLE
Trakt Uninitialized

### ISSUE THREAD

**Issue by gahmasec** [bonukai/MediaTracker#450]
After installing the service with docker, everything works fine except Trakt. When I click on import it simply shows this message "Uninitialized" . Does anyone know what can it be?

**Comment by BanCrash** [comment]
> After installing the service with docker, everything works fine except Trakt. When I click on import it simply shows this message "Uninitialized" . Does anyone know what can it be?

Trakt api is disabled until (at least) next week. https://twitter.com/trakt/status/1604114567579111425
