### ISSUE TITLE
Entering year manually changes the day

### ISSUE THREAD

**Issue by filcuk** [bonukai/MediaTracker#471]
Below I enter full date into the 'When did you play/watch xyz?` window. 
When entering year, the day is moved to 3 days earlier:
![date](https://user-images.githubusercontent.com/1339532/212483355-4d81ffdf-f1fc-4f7f-9b4d-032dad4a348f.gif)

It can (from my experience) be reproduced easily with any combination of dates.
I'm on the latest docker release.

**Comment by bonukai** [comment]
Fixed in `0.1.0-beta.42`

**Comment by filcuk** [comment]
Can confirm, thanks!
