### ISSUE TITLE
[suggestion] Change 'Custom date' default time to 00:00

### ISSUE THREAD

**Issue by filcuk** [bonukai/MediaTracker#472]
To enter current date & time, we can use the `Now` button.  
When entering a custom date, the date & time is unlikely to be the same as current time.
There's a good chance (IMO) that the time won't be known at all.

This is why I suggest to:
- Default custom time be 00:00
or
- The `x` button resets time to 00:00 (instead of current time)

**Comment by bonukai** [comment]
Thank you, I agree with your suggestion, it have been implemented in `0.1.0-beta.42`

**Comment by filcuk** [comment]
Brilliant, thank you!
