### ISSUE TITLE
No UI to add items?

### ISSUE THREAD

**Issue by xdpirate** [bonukai/MediaTracker#480]
Hey there, I feel like I'm going crazy, is there no interface in the web UI to add new items to MediaTracker? I can't find functionality to do this on the online demo, and after setting up the docker image and running it, there is no such functionality there either. I've tried both on Firefox and Chromium. There is also zero documentation about the usage of MediaTracker in the readme, which makes it even harder to know what to do, if I have to manage the database manually/by API calls then that should be mentioned somewhere in the readme.

Am I doing something wrong or isn't there supposed to be a big ol' plus button somewhere to add items to the database through the UI? When running locally in docker I am also missing the "Lists" option that shows on the demo instance.

I'm running MediaTracker in docker-ce with the :latest image on KDE neon user edition. All blocking through uBlock etc is disabled on localhost.

Any help would be greatly appreciated! This is what the UI looks like for me:

![image](https://user-images.githubusercontent.com/1757462/221047210-bbb7de96-a3eb-4d26-b6ea-80c828c279dc.png)

**Comment by bonukai** [comment]
You can search for items in any category (for games you have to add your own IGDB api key), after that you will be able to add those items to watchlist or seen history. 

For lists you can use `mediatracker:unstable` docker image

**Comment by xdpirate** [comment]
Thanks!
