### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by joopdo** [bonukai/MediaTracker#485]
`mediatracker The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s`

For your information, I could not use docker-compose as there is no arm64/v8 build.

Keep up the great work!

**Comment by bonukai** [comment]
Now there are `amd64`, `arm/v6`, `arm/v7` and `arm64` builds available for both `stable` and `unstable` releases

**Comment by joopdo** [comment]
Thank you sir!
