### ISSUE TITLE
Error in trying to import from Goodreads

### ISSUE THREAD

**Issue by IgnisDa** [bonukai/MediaTracker#486]
I am getting this error:

![image](https://user-images.githubusercontent.com/60938164/228572296-d1405600-a3f0-4f4c-af91-55e8a09cb0d0.png)

**Comment by bonukai** [comment]
This has been fixed in `0.1.0-beta.42` version

**Comment by IgnisDa** [comment]
Yes. Tested with the [unstable](https://hub.docker.com/layers/bonukai/mediatracker/unstable/images/sha256-46c706733764359f095142ad7a68a46f68307b9e19d991b9c9a65ef839e21631?context=explore) image. Thanks!
