### ISSUE TITLE
Copy to clipboard import button is not working

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#488]
Hi, on WIP branch, building from source using npm, the "Copy to clipboard" button on the import page is not copying to clipboard the trakt.tv code.

I mean, this button ("Copiar al portapapeles" = "Copy to clipboard").

![imagen](https://user-images.githubusercontent.com/11770760/233775163-24ff1ec0-cda0-474c-9a4a-f86257208fa6.png)

If I click it nothing is copied to the clipboard, the previous item will be pasted when using Ctrl + V shortcut on trakt.tv importing page.

EDIT: Okay, it seems that the issue happens only using Firefox. In chrome works as expected.

**Comment by bonukai** [comment]
Now it should work in all browser

**Comment by BanCrash** [comment]
> Now it should work in all browser

Fixed in firefox with last commit!
