### ISSUE TITLE
Lists only show 10 items

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#489]
Hi, another issue I've found on WIP branch, lists only show 10 items, even if they have a lot more.

For example ("44 elementos" = "44 items"):
![imagen](https://user-images.githubusercontent.com/11770760/233775499-d531cc3c-d675-45f1-8d62-ee61c7508c52.png)

On my watchlist, I have 44 items, but when I enter on it, it will only show 10 items:
![imagen](https://user-images.githubusercontent.com/11770760/233775516-19de8b6c-f46c-41dc-98e9-3ac8bf2af9ea.png)

("10 elementos" = "10 items")

**Comment by bonukai** [comment]
This was leftover from testing, now all items are returned. Thank you for testing :)

**Comment by BanCrash** [comment]
Yep, fixed on last WIP commit!
