### ISSUE TITLE
How do I start over with docker?

### ISSUE THREAD

**Issue by phirestalker** [bonukai/MediaTracker#495]
I mistakenly used the tag latest and tried to run an import from trakt. I cut that short and changed to unstable. Then I tried to boot up and got some database error. I figured I could just drop all the tables from the postgres db. I still get the error. I bring down mediatracker delete tables again, purge -a on docker images. I thought that would give me a blank slate. Nope, I still get the error instead of the registration screen.

How do I wipe out everything and start over? What docker commands did I miss?

EDIT:
here is the error
```
500: Server error
error: update "mediaItem" set "tmdbId" = $1 where "tmdbId" = $2 - invalid input syntax for integer: ""
```

**Comment by phirestalker** [comment]
ya this is something else. I just switched to the main branch in my other directory and built and started an image from that and I get a different error.

```
500: Server error
Error: The migration directory is corrupt, the following files are missing: 20220603191400_listTraktId.js, 20230205000000_uniqueExternalIds.js, 20230218000000_seenIndex.js, 20230422000000_updateListRanks.js
```

**Comment by bonukai** [comment]
I've just updated migration to work on postgres, so the error from first post shouldn't occur anymore. As for the second one, at the moment migrations cannot be reversed, if you used the database with newer version of MediaTracker, you wont be able to use if later with a previous version of MediaTraker.

**Comment by phirestalker** [comment]
That fixed it, thanks. After I posted I suspected the second issue was something like that.
