### ISSUE TITLE
Ability to put Season 2+ on watchlist

### ISSUE THREAD

**Issue by syberslxt** [bonukai/MediaTracker#500]
Lets take the anime `Spy x family` as an example.
This anime came out in 2022. Lets suppose i have finished watching Season 1 back in 2022, and put the anime as "watched/seen".

![image](https://user-images.githubusercontent.com/4239073/236645851-596df8ac-75ae-40be-be93-032498238e71.png)

Now, season 2 is scheduled for Oct 2023.

![image](https://user-images.githubusercontent.com/4239073/236645836-476867f3-ce12-4049-b97e-6a83100a9080.png)

In the calendar, i can go back to 2022 and see indeed that `Spy x family` listed. However, the new seasons do not get set in the calendar (say, Oct 2023).

![image](https://user-images.githubusercontent.com/4239073/236645861-a9f7c16f-eba7-4528-adf8-47c2b76cceb5.png)

I am suspecting that perhaps in the metadata there is no specific date? So for example instead of 01-Oct-2023 it is only Oct-2023?

PS: I have known about MediaTracker for a while, but just started using it. And I would like to mention that I really appreciate the developer and all the contributors to make this an even amazing product! <3

**Comment by bonukai** [comment]
Metadata for movies and TV shows is from [TMDB](https://www.themoviedb.org/), and there there is just one season of [SPY x FAMILY](https://www.themoviedb.org/tv/120089-spyxfamily)](https://www.themoviedb.org/tv/120089-spyxfamily/seasons).

Metadata is frequently updating, and once there will be specific date for new episodes, where will be on your calendar.
