### ISSUE TITLE
Internal Server Error at calendar

### ISSUE THREAD

**Issue by xrfmkrh** [bonukai/MediaTracker#504]
version : 0.1.0-beta.43, 0.1.0-beta.44
when i click calendar, it shows server error: 500 (Internal Server Error)

**Comment by jonkristian** [comment]
I can reproduce this if I import many things from trakt for instance the calendar crashes. Also the API endpoint seem to have some issues as well, might be related:

``
Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [releaseDate] query: select *, `seen`.`episodeId` as `seen` from `episode` inner join (select * from `watchlist` where `userId` = ?) as `watchlist` on `watchlist`.`mediaItemId` = `episode`.`tvShowId` left join (select distinct `mediaItemId`, `episodeId` from `seen` where `userId` = ?) as `seen` on `seen`.`episodeId` = `episode`.`id` where `releaseDate` between ? and ? and `isSpecialEpisode` = ? order by `seasonNumber` asc, `episodeNumber` asc
``

**Comment by bonukai** [comment]
Both of those errors are fixed in the latest version `0.1.0`
