### ISSUE TITLE
Server language fr not available

### ISSUE THREAD

**Issue by Turiok** [bonukai/MediaTracker#505]
Hi,

It seems in source code french language is available. In documentation too.
But If I add environment variable ```SERVER_LANG=fr``` , it doesn't work.
And IHM too : 
![image](https://github.com/bonukai/MediaTracker/assets/6814217/16f5cd03-db9d-48f3-92d7-39982732614d)

**Comment by xrfmkrh** [comment]
you have to change your browser language to French

**Comment by bonukai** [comment]
Please use the latest version `0.1.0`
