### ISSUE TITLE
Error while getting details about some items

### ISSUE THREAD

**Issue by IgnisDa** [bonukai/MediaTracker#513]
![image](https://github.com/bonukai/MediaTracker/assets/60938164/11bc4687-d666-428a-ab27-12b6ddf7b87c)

The same happens for items: `330` and `331`.

**Comment by bonukai** [comment]
Could you please show the server logs, either from console, or from web interface at `#/settings/logs`

**Comment by IgnisDa** [comment]
This is actually the demo instance (https://mediatracker.app). I do not have access to the logs/

**Comment by bonukai** [comment]
Ok, I didn't notice that, thank you :)

**Comment by bonukai** [comment]
fixed in version `0.2.1`
