### ISSUE TITLE
Feature to add comment or personnal note

### ISSUE THREAD

**Issue by Turiok** [bonukai/MediaTracker#525]
Hi,

Thanks for the work.

I'm using MediaTracker to know what I've seen even If I have deleted the media.
I would like to have the possibility to add comment on media.
Sometimes I begin  a TV show but I don't like it. I would like to add it on MediaTracker to know to not seen again the show

**Comment by bonukai** [comment]
At the moment you can use reviews for this.

Closing, as this is a duplicate of #63
