### ISSUE TITLE
Set and change different database location than .mediatracker

### ISSUE THREAD

**Issue by superbonaci** [bonukai/MediaTracker#538]
Database file, logs and assets will be saved in `$HOME/.mediatracker`.
It's configured in './server/src/config.ts:24'
That name is too generic and can be used by other programs, so this is a feature request to be able to set or change `configDirectory`. For example:

- `$HOME/.bonukai.mediatracker`
- `$HOME/.bonukai-mediatracker`
- `$HOME/.bonukai_mediatracker`
- `$HOME/.mediatracker.bonukai`
- `$HOME/.mediatracker-bonukai`
- `$HOME/.mediatracker_bonukai`

This is to make it compatible with forks or other random software.

**Comment by IgnisDa** [comment]
If you use docker, you can mount any directory from your host to this directory.

**Comment by superbonaci** [comment]
But that's the issue, that I don't want to use that directory. I could edit the config.ts file but then would be more difficult to fetch new git pulls.

**Comment by IgnisDa** [comment]
In that case, you could make a PR perhaps? Sounds easy enough to fix.

**Comment by bonukai** [comment]
`$HOME/.mediatracker` is a default directory for storing a SQLite database, logs and assets. If you use Docker, you can mount them in directories of your choice when specifying volumes.

If you do not use Docker, you can control those directories with environmental variables: `DATABASE_PATH`, `ASSETS_PATH`, `LOGS_PATH`
