### ISSUE TITLE
Cannot link it to a standalone jellyfin lxc instance

### ISSUE THREAD

**Issue by gh-IN** [bonukai/MediaTracker#549]
Hi,

Thank you for developing and maintaining this app - I installed it today using "npm install -g mediatracker" command on my windows 10 pc, through powershell, and I can access the app on my web browser through "localhost:7481" or "127.0.0.1:7481". However, the page is not accessible through "<my-pc-local-ip>:7481" on either my pc browser or other devices on my LAN, and therefore, I am not able to link its API token to a jellyfin server running on a distinct lxc in my network.

Could you please share any guidance on resolution or let me know if any additional detail is needed to investigate/resolve the issue.

P.S. I am new to this community, so please do let me know in case I am missing something obvious or in case this is not the right channel to seek resolution.

**Comment by bonukai** [comment]
By default the server will listen on the `localhost`, so it won't be accessible from other computers on the network. This can be changed with an environment variable `HOSTNAME`:
```PowerShell
$Env:HOSTNAME="0.0.0.0"
```
on PowerShell, or
```cmd
set HOSTNAME=0.0.0.1
```
Command Prompt.

I updated README with this environment variable.

**Comment by gh-IN** [comment]
Thank you so much for the prompt resolution, the PowerShell command worked like a charm!

Will close this thread.
