### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by NerdySouth** [bonukai/MediaTracker#560]
Loving the app. I was digging around looking for how to enable HTTPS, but came up empty handed. It would be super nice to be able to provide a cert and key file for the app to use in docker for HTTPS. Pretty much all my services use HTTPS, so it would be super nice to have this one in line. I would be happy to begin working on this personally if I can get a few pointers for where to start digging into the codebase (relevant directories/files for the connection setup). Overall great project!

**Comment by IgnisDa** [comment]
Won't it be easier to plop a reverse proxy in front and enable HTTPs on that level?

**Comment by NerdySouth** [comment]
Got this working fine, sorry for clogging the issue tracker.
