### ISSUE TITLE
Add to Seen History (Mark As Seen) Doesn't Work With All TV Shows

### ISSUE THREAD

**Issue by gabeanelson** [bonukai/MediaTracker#6]
There appears to be a limit to the number of episodes you can mark as seen. For instance, with Saturday Night Live (SNL), on the popup of "What is the last episode you seen?", if you pick the current season/episode (42/3), nothing happens. If you select season 25, episode 20, those episodes will be marked as seen. I'm not sure why I can't mark all of the SNL episodes as seen, but without that ability, it messes up the home screen's "Next episode to watch" suggestions.

**Comment by bonukai** [comment]
Thank you for giving detailed explanation. When inserting large number of rows, generated SQL query was too long. This should be now fixed.
