### ISSUE TITLE
Support Jellyfin 10.9.1 via plugin possible ?

### ISSUE THREAD

**Issue by SkalCore** [bonukai/MediaTracker#615]
Jellyfin 10.9.1 was recently released, with the plugin of mediatracker it was comfortably possible to use mediatracker. Is there a rough schedule when the plugin will be compatible again?

**Comment by bonukai** [comment]
Plugin has been updated to Jellyfin 10.9.1

**Comment by lyz-code** [comment]
Shall the issue be closed then?
