### ISSUE TITLE
WIP: Lists page is broken (+1 line fix)

### ISSUE THREAD

**Issue by ramebd** [bonukai/MediaTracker#645]
**WIP branch** issue

[This line](https://github.com/bonukai/MediaTracker/blame/2c839a81a6c08303191a47422aa8fe08de86fda1/src/repository/listRepository.ts#L328) breaks the ListItem page when viewing the details of a List (/list/#) because it adds an OrderBy to the countRes query which only does a select count(*) and errors on Postgres:

No matter what the sort order is: 
```
ERROR: error: select count(*) as "count" from "listItem" left join "mediaItem" on "listItem"."mediaItemId" = "mediaItem"."id" where "listId" = $1 order by "addedAt" asc - column "listItem.addedAt" must appear in the GROUP BY clause or be used in an aggregate function
```
or this:
```
ERROR: error: select count(*) as "count" from "listItem" left join "mediaItem" on "listItem"."mediaItemId" = "mediaItem"."id" left join "episode" on "mediaItem"."upcomingEpisodeId" = "episode"."id" where "listId" = $1 and (("mediaItem"."mediaType" <> $2 and "mediaItem"."releaseDate" > $3) or ("mediaItem"."mediaType" = $4 and "episode"."releaseDate" > $5)) order by CASE
          WHEN "mediaItem"."mediaType" = 'tv' THEN "episode"."releaseDate"
          ELSE "mediaItem"."releaseDate"
        END asc NULLS LAST - column "mediaItem.mediaType" must appear in the GROUP BY clause or be used in an aggregate function
```

Basically, you can't order by a column if it's not in the select list.

But, I saw [your comment](https://github.com/bonukai/MediaTracker/pull/644/commits/ad170319751f6823286ddb24fa1bf62d7e2f7bd3#r1865131316):
> sorting by 'next-airing' removes items that do not have an 'next-airing', so filterQuery is required

Now I get it 😄  

sortQuery() is actually adding some Joins & Wheres that are required to filter the results based on the sort option selected separate to the filterQuery(). Which is fine for the listItems, but the countRes is broken (in postgres at least) because sortQuery also adds an Order By. 

After a bit of fiddling around with sniffing the selected columns in the querybuilder, I think the absolute simplest solution is to just leave sortQuery as-is, then put a .clear('order') in the pipeline after the sortQuery(). eg:
```
      const countRes = await trx('listItem')
        .where('listId', listId)
        .leftJoin('mediaItem', 'listItem.mediaItemId', 'mediaItem.id')
        .modify((qb) => filterQuery(qb, args))
        .modify((qb) => sortQuery(qb, args))
        .clear('order')   // <---- just add this line to make sure the count(*) never tries to OrderBy anything
        .count({ count: '*' });
```

**Comment by bonukai** [comment]
This has been resolved in #646

Now sorting doesn't filter queries :)
