### ISSUE TITLE
where to find mediaitemid?

### ISSUE THREAD

**Issue by Fabaderheld** [bonukai/MediaTracker#7]
Sorry to bother you again but ```/api/watchlist``` requires the ```mediaitemid``` where can I find it?
thanks again
Faba

**Comment by bonukai** [comment]
It's no problem at all, feel free to ask any questions, or request for API routes.

`mediaItemId` is an `id` field returned from `/api/search` and `/api/routes`. I will later add routes, where you can use title and release year instead

**Comment by Fabaderheld** [comment]
Thanks for the quick reply. I was looking at ```/api/search``` but couldn't find it there.
Regards
Faba

**Comment by Fabaderheld** [comment]
FYI I figured it out and could add shows to the watchlist
