### ISSUE TITLE
Docker: Error while start up - Cannot find module '/app/build/src/index.js

### ISSUE THREAD

**Issue by URBANsUNITED** [bonukai/MediaTracker#70]
Sorry, can't edit the topic.
Docker: Error while start up - Cannot find module '/app/build/src/index.js
should be the correct one.

Hi!

I've just pulled the latest docker image from Docker hub and get this error while start up:
Digest: e7fd119f3aec

```
node:internal/modules/cjs/loader:936

  throw err;
  ^
Error: Cannot find module '/app/build/src/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v17.4.0
```

**Comment by bonukai** [comment]
This error was fixed couple days ago, could you try to pull the image again, with command
```
docker pull bonukai/mediatracker:latest
```

**Comment by URBANsUNITED** [comment]
Strange...
Now it works. Pulled several times the latest images, including recreation - always the same. Now, I did exactly the same and it works.
