### ISSUE TITLE
Bugs: Text not readable TV episodes overview & Genres are incorrect

### ISSUE THREAD

**Issue by URBANsUNITED** [bonukai/MediaTracker#71]
Hi!

As written above,
the text in the episodes overview is unreadable and the text "Genres" is not correct:

![Bildschirmfoto 2022-02-06 um 11 11 32](https://user-images.githubusercontent.com/6212300/152676274-6fb6adcc-6cc6-43f1-99f3-88b434b88fab.png)

The text is there, but only seeable by marking:

![Bildschirmfoto 2022-02-06 um 11 15 48](https://user-images.githubusercontent.com/6212300/152676322-a0203dbd-9ff4-446a-8f87-900d80a52ec1.png)

I am using Chrome, normally Safari too, but here I can't open the page.  Will investigate later... On the iPhone page works.

![Bildschirmfoto 2022-02-06 um 11 10 46](https://user-images.githubusercontent.com/6212300/152676281-17654d53-ee75-4863-9d50-5925bffd6ef3.png)

**Comment by bonukai** [comment]
Episode overview is hidden by design, to avoid spoilers. It should be visible on mouse hover, or a tap on devices with a touchscreen. After marking episode as seen, it's not hidden anymore.

I will add an option to configure this behavior

**Comment by URBANsUNITED** [comment]
Ok! understand. Makes sense, but making it optional fits, so do I believe, better for everybody.

Thanks

What with my second point? The marked area? Spelling issue?

**Comment by bonukai** [comment]
Spelling bugs should now be fixed

**Comment by URBANsUNITED** [comment]
New translation finished.

Please correct this here:
![image](https://user-images.githubusercontent.com/6212300/152754479-20dd87e5-43ee-4075-a914-c0dbabdcc521.png)

**Comment by bonukai** [comment]
You can now change settings for hiding episode title and season overview in settings/preferences

**Comment by URBANsUNITED** [comment]
Missing translation on server side:
{0, plural, one {Updating metadata for # item} other {Updating metadata for # items}}

**Comment by bonukai** [comment]
I finally figured out the root cause of this issue

**Comment by URBANsUNITED** [comment]
Mmmmhh Not fully.
It doesn't keep the server language saved:
I've changed within the Website the server language even it was set to german. All was fine right after. Then I've restarted the container and it was english again:

![Bildschirmfoto 2022-02-09 um 17 25 06](https://user-images.githubusercontent.com/6212300/153244585-17177891-050d-4166-b92f-e7049732b703.png)

Also The dropdown list here is always on the first entry, even they are set to german for example in the env.:

![Bildschirmfoto 2022-02-09 um 17 27 48](https://user-images.githubusercontent.com/6212300/153244793-a08d20d7-de58-46da-8bac-ee3319d70c57.png)

**Comment by bonukai** [comment]
Server language should now be fixed.

Audible and TMDB language had different values in environment values and in UI, `DE` vs `de` and `de-DE` vs `de`. Now `SERVER_LANG`, `TMDB_LANG` and `AUDIBLE_LANG` environment variables are validated, so those values should be the same everywhere

**Comment by URBANsUNITED** [comment]
TOP!!!!
Looks very good. Problem solved

One question:
Where is the time coming from:

![Bildschirmfoto 2022-02-09 um 18 56 14](https://user-images.githubusercontent.com/6212300/153261155-b28900d4-f4a7-492d-b7ca-33cdd521ec57.png)

Not sync with the server I believe. I don't know if it is relevant. But maybe people care about... I don't ;)

**Comment by URBANsUNITED** [comment]
Right! Works!
![Bildschirmfoto 2022-02-09 um 20 09 09](https://user-images.githubusercontent.com/6212300/153272666-d7b86fbd-c7f6-4250-992d-d64d1d472766.png)
Thanks
