### ISSUE TITLE
Results of movies and tv series still in english even after changing the language

### ISSUE THREAD

**Issue by BanCrash** [bonukai/MediaTracker#74]
Hello!

I installed the tracker today and set Spanish as TMBD language, but the results still are presented in english.

I don't know if I have to do something else:

![image](https://user-images.githubusercontent.com/11770760/152804235-385fa1c3-bab6-4a65-8cbc-910e9fe1d3ef.png)

Btw, I will translate this project to spanish when I have some little time.

**Comment by bonukai** [comment]
Searching for items, that you never search before should now be in selected language, but you will have to set the language again. 

After changing TMDB language your entire database should update itself. 

Now I am rewriting search queries, so all search result should show in selected language.

Thank you for Spanish translations :)

**Comment by BanCrash** [comment]
> Searching for items, that you never search before should now be in selected language, but you will have to set the language again., there was a small bug.
> 
> After changing TMDB language your entire database should update itself.
> 
> Now I am rewriting search queries, so all search result should show in selected language.
> 
> Thank you for Spanish translations :)

Perfect, now it's working as expected, thanks!

My pleasure! I will work on translate the remaining strings from time to time.

And thank you for this awesome program!
