### ISSUE TITLE
Mark Season as watched

### ISSUE THREAD

**Issue by CountMurphy** [bonukai/MediaTracker#9]
Typically I prefer to wait until a season is finished before starting to watch, and use apps similar to this (though less featured) to alert me when the new season starts/finishes. Having the ability to mark the entire season as viewed is much more convenient than having to mark each episode.

**Comment by bonukai** [comment]
There is ability to mark season as watched from episodes page. It will open a modal "What is the last episode you seen?", where you can select last episode to mark as, seen. When selected last episode (default), entire season will be marked as seen.

I changed this button's text to "Add season to seen history".

Any ideas how I could make it easier to spot?. Making good UI is really hard.

**Comment by CountMurphy** [comment]
> Do you have any ideas how I could make it easier to spot? Making good UI is really hard.
I hear that. You should see my projects, lol.

This all makes a lot more sense now. Not really sure how to make it easier to spot. Maybe turning the episode link to a button? Not critical either way but that's my two cents.
